spring.application.name=backend
server.port=8081

# Koneksi ke Database PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/acc_approval_db
spring.datasource.username=postgres
spring.datasource.password=Mftkhrkhmn_69
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true